
# Database index
# spring.redis.database=1
# spring.redis.host=106.10.54.127
# spring.redis.ssl=false
# spring.redis.port=6379
spring:
  redis:
    database: 1
    host: 106.10.54.127
    port: 6379
    ssl: false
    